### PR TITLE
Initial Main Menu

### PR DESCRIPTION
**Pull request by danieldownes**
- Created a new graphical menu using SFML, replacing the console-based menu.
- Added clickable buttons and borders for menu options.
- Enabled key press support for menu selection.

# Code Refactor:

- Separated the menu-related code into MainMenu.h and MainMenu.cpp.
- Created TheGreatWar.h to declare necessary components and functions for the main game logic.
- Kept the main game logic in TheGreatWar.cpp.

### CODE REVIEW

**Comment by danieldownes** [comment]
WIP

**Comment by danieldownes** [comment]
If we are just going fullscreen then probably we don't need to create a seperate window for the menu at all.

**Comment by 123samueld** [comment]
> If we are just going fullscreen then probably we don't need to create a separate window for the menu at all.

I agree, it just seems like a neat solution and for the sake of a prototype it works just fine. So I think it's fine to leave most of it, go full screen and move on. Full screen is because later we'll add some art to the background and want to cover the whole window.

**Comment by danieldownes** [comment]
@123samueld Done, but of course you now briefly get dropped back to the desktop before the next window shows.

**Comment by danieldownes** [comment]
I think there should be a option to keep to windowed mode anyway for development. Its much more comfortable to not have to go into full-screen all the time when working on something.

**Review by 123samueld — APPROVED** [review]
Thank you for the new menu, this was prep for someone else's branch in a bit.

**Pull request merged**
