### PR TITLE
1 boid follows the pathfinder agent

### PR DESCRIPTION
**Pull request by LiamStewart2**

### CODE REVIEW

**Comment by danieldownes** [comment]
Looking good. The only improvement would be that the tweaning does not move up and down terrain elevation smoothly, but would suggest this is not a blocker for this PR unless its quick to add.

**Review by 123samueld — CHANGES_REQUESTED** [review]
This is looking really good. Please just remove the "no path found" console message and this is ready to merge.

**Comment by 123samueld** [comment]
> Looking good. The only improvement would be that the tweaning does not move up and down terrain elevation smoothly, but would suggest this is not a blocker for this PR unless its quick to add.

The Agent that isn't tweaning correctly is actually just a Pathfinder Agent, which won't be visible in the actual game. Good point about tweening though, I'll check if there are libraries that could help with that, especially for adapting movement speed going up/down hills.

**Review by 123samueld — CHANGES_REQUESTED** [review]
Dan has made a good point about the movement speed of the MobileAgent, which is that it's speed is not affected by the hills, this will need updated so travelling up a hill slows movement and traveling down a hill increases movement speeds.

**Review by danieldownes — APPROVED** [review]
Looking sweet. I don't see the update jitter actually on this branch.

**Pull request merged**
